# Generated by Django 2.2.11 on 2020-03-06 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste1', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmado', models.BooleanField(default=False)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('cep', models.CharField(max_length=10, null=True)),
                ('pais', models.CharField(max_length=20, null=True)),
                ('estado', models.CharField(max_length=20, null=True)),
                ('cidade', models.CharField(max_length=20, null=True)),
                ('logradouro', models.CharField(max_length=200, null=True)),
                ('complemento', models.CharField(max_length=200, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagem_perfil', models.ImageField(blank=True, default='user_image.png', null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
