# Generated by Django 3.0.3 on 2020-02-27 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contas', '0002_auto_20200227_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('cep', models.CharField(max_length=10, null=True)),
                ('pais', models.CharField(max_length=20, null=True)),
                ('estado', models.CharField(max_length=20, null=True)),
                ('cidade', models.CharField(max_length=20, null=True)),
                ('logradouro', models.CharField(max_length=200, null=True)),
                ('complemento', models.CharField(max_length=200, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagem_perfil', models.ImageField(blank=True, default='user_image.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
