# Generated by Django 2.1 on 2020-03-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20200227_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
